name: Security scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 #! Important for gitleaks to check the history

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - name: Install security tools
        run: pip install bandit pip-audit

      - name: Run Bandit (Python Static Analysis)
        #? Checking for false checks
        run: bandit -r backend/ -f json -o bandit.json || true

      - name: Run pip-audit (Dependency Vulnerabilities)
        run: |
          cd backend
          pip-audit -r requirements.txt --format json -o pip-audit.json || true

      - name: Run Gitleaks (Secret Detection)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}